include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    no_logic_in_create_state: false
    library_private_types_in_public_api: false

extensions:
  - provider: true